### ISSUE TITLE
[BUG] panic: no Auth Provider found for name "azure"

### ISSUE THREAD

**Issue by thiagorider** [cloud-bulldozer/kube-burner#139]
**Output of `kube-burner` version**

```
$ kube-burner version
Version: 0.14.2
Git Commit: 35fb3d9c697eb50fb055c175ad546154dcaa4dd3
Build Date: 2021-10-25T06:52:24Z
Go Version: go1.16.9
OS/Arch: linux amd64
```

**Describe the bug**
Can't run kube-burner with Azure Kubernetes Service. After cloning https://github.com/cloud-bulldozer/kube-burner repo for examples, I've tried using kube-burner api-intensive setup on AKS. My KUBECONFIG variable was set to point to a valid cluster config file and kube-burner crashes as shown in **Screenshots or output**

**To Reproduce**
1. Get kube-burner binary from https://github.com/cloud-bulldozer/kube-burner/releases and extract to _~/kubeburner_
2. Copy kube-burner binary to _~/.local/bin_
3. Reload shell.
3. Clone kube-burner for examples in _~/kubeburner/kube-burner.git_
3. Change dir to _~/kubeburner/kube-burner.git/examples/workloads/api-intensive_
4. Edit _api-intensive.yml_ setting _indexerConfig:enabled_ to _false_.
5. Run: `$ kube-burner init --config api-intensive.yml`

**Expected behavior**
I was expecting several k8s objects are to created and kube-burner could communicate with AKS cluster.

**Screenshots or output**
```
$ kube-burner init --config api-intensive.yml
INFO[2021-10-25 20:37:23] 🔥 Starting kube-burner (0.14.2@35fb3d9c697eb50fb055c175ad546154dcaa4dd3) with UUID d9e3d2f6-7e7c-45df-af97-0779c5d86c9b 
panic: no Auth Provider found for name "azure"

goroutine 1 [running]:
k8s.io/client-go/kubernetes/typed/admissionregistration/v1.NewForConfigOrDie(...)
	/home/runner/work/kube-burner/kube-burner/vendor/k8s.io/client-go/kubernetes/typed/admissionregistration/v1/admissionregistration_client.go:64
k8s.io/client-go/kubernetes.NewForConfigOrDie(0xc0006add40, 0x32)
	/home/runner/work/kube-burner/kube-burner/vendor/k8s.io/client-go/kubernetes/clientset.go:588 +0x1513
github.com/cloud-bulldozer/kube-burner/pkg/config.GetClientSet(0x0, 0x0, 0x0, 0x29fab00, 0x0, 0x0)
	/home/runner/work/kube-burner/kube-burner/pkg/config/config.go:189 +0x138
main.steps(0xc00041a510, 0x24, 0x0, 0x0)
	/home/runner/work/kube-burner/kube-burner/cmd/kube-burner/kube-burner.go:314 +0x5f
main.initCmd.func1(0xc0003e9900, 0xc0004a1080, 0x0, 0x2)
	/home/runner/work/kube-burner/kube-burner/cmd/kube-burner/kube-burner.go:129 +0x2fc
github.com/spf13/cobra.(*Command).execute(0xc0003e9900, 0xc0004a1060, 0x2, 0x2, 0xc0003e9900, 0xc0004a1060)
	/home/runner/work/kube-burner/kube-burner/vendor/github.com/spf13/cobra/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x29b64c0, 0x0, 0x0, 0x0)
	/home/runner/work/kube-burner/kube-burner/vendor/github.com/spf13/cobra/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/work/kube-burner/kube-burner/vendor/github.com/spf13/cobra/command.go:897
main.main()
	/home/runner/work/kube-burner/kube-burner/cmd/kube-burner/kube-burner.go:408 +0x2f2
```

**Additional context**

```
$ uname -a
Linux thiago-Latitude-5410 5.11.0-37-generic #41~20.04.2-Ubuntu SMP Fri Sep 24 09:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

$KUBECONFIG var is populated with path to kubeconfig file:
```
$ echo $KUBECONFIG 
/home/thiago/config-myakscluster
```

My kubeconfig file looks like:
```
$ cat $KUBECONFIG
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: XXXXXXXXXXXX
    server: https://api-myakscluster-0000000.hcp.eastus2.azmk8s.io:443
  name: myakscluster
contexts:
- context:
    cluster: myakscluster
    user: clusterUser_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  name: myakscluster
current-context: myakscluster
kind: Config
preferences: {}
users:
- name: clusterUser_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  user:
    auth-provider:
      config:
        apiserver-id: XXXXXXXXXXXXXXXXXXXXXXXX
        client-id: XXXXXXXXXXXXXXXXXXXXXXXXXX
        environment: AzurePublicCloud
        tenant-id: XXXXXXXXXXXXXXXXXXXXXXXXX
      name: azure
```

This kubeconfig is generated by the following AzCLI command :
`az aks get-credentials [...] -f  ~/.config-myakscluster`
It is perfectly valid and works with kubectl.

**Comment by thiagorider** [comment]
Hi @rsevilla87 ! It worked! Thanks!

**Comment by thiagorider** [comment]
```
$ kube-burner init --config api-intensive.yml
INFO[2021-11-01 21:38:50] 🔥 Starting kube-burner (latest@418816b7d740da7468e7ecf54278108db58c6409) with UUID c6db63ec-b5e9-41e3-b77d-10a7016a44e3 
INFO[2021-11-01 21:38:50] 📈 Creating measurement factory               
INFO[2021-11-01 21:38:50] Registered measurement: podLatency           
INFO[2021-11-01 21:38:50] Preparing create job: api-intensive          
INFO[2021-11-01 21:38:50] Job api-intensive: 700 iterations with 1 Deployment replicas 
INFO[2021-11-01 21:38:50] Job api-intensive: 700 iterations with 1 ConfigMap replicas 
INFO[2021-11-01 21:38:50] Job api-intensive: 700 iterations with 1 Secret replicas 
INFO[2021-11-01 21:38:50] Job api-intensive: 700 iterations with 1 Service replicas 
INFO[2021-11-01 21:38:50] Preparing delete job: api-intensive-remove   
INFO[2021-11-01 21:38:50] Job api-intensive-remove: Delete Deployment with selector kube-burner-job=api-intensive 
INFO[2021-11-01 21:38:50] Preparing delete job: ensure-pods-removal    
INFO[2021-11-01 21:38:50] Job ensure-pods-removal: Delete Pod with selector kube-burner-job=api-intensive 
INFO[2021-11-01 21:38:50] Preparing delete job: remove-services        
INFO[2021-11-01 21:38:50] Job remove-services: Delete Service with selector kube-burner-job=api-intensive 
INFO[2021-11-01 21:38:50] Preparing delete job: remove-configmaps-secrets 
INFO[2021-11-01 21:38:50] Job remove-configmaps-secrets: Delete ConfigMap with selector kube-burner-job=api-intensive 
INFO[2021-11-01 21:38:50] Job remove-configmaps-secrets: Delete Secret with selector kube-burner-job=api-intensive 
INFO[2021-11-01 21:38:50] Triggering job: api-intensive                
INFO[2021-11-01 21:38:51] Creating Pod latency informer for api-intensive 
INFO[2021-11-01 21:38:51] QPS: 4                                       
INFO[2021-11-01 21:38:51] Burst: 4                                     
INFO[2021-11-01 21:38:51] Running job api-intensive
```
